const generate = require("../index");

test("generate", () => {
  expect(generate("test/fixtures/SimpleRecord.elm"))
    .toBe(`-- This module is generated by \`setem\` command. DO NOT edit manually!


module RecordSetter exposing (..)


s_f1 : a -> { b | f1 : a } -> { b | f1 : a }
s_f1 value record =
    { record | f1 = value }


s_f2 : a -> { b | f2 : a } -> { b | f2 : a }
s_f2 value record =
    { record | f2 = value }


s_f3 : a -> { b | f3 : a } -> { b | f3 : a }
s_f3 value record =
    { record | f3 = value }


s_f3_f1 : a -> { b | f3_f1 : a } -> { b | f3_f1 : a }
s_f3_f1 value record =
    { record | f3_f1 = value }


s_f3_f2 : a -> { b | f3_f2 : a } -> { b | f3_f2 : a }
s_f3_f2 value record =
    { record | f3_f2 = value }
`);
});
