const parse = require("../index");

test("parse", () => {
  const elmSource = `
module Main exposing (..)

type alias R =
    { f1 : String
    , f2 : Int
    , f3 : { f3_f1 : Bool, f3_f2 : List Float }
    }

r =
    { f1 = ""
    , f2 = 1
    , f3 = { f3_f1 = True, f3_f2 = [] }
    }
`;
  expect(parse(elmSource))
    .toBe(`-- This module is generated by \`setem\` command. DO NOT edit manually!


module RecordSetter exposing (..)


s_f1 : a -> { b | f1 : a } -> { b | f1 : a }
s_f1 value record =
    { record | f1 = value }


s_f2 : a -> { b | f2 : a } -> { b | f2 : a }
s_f2 value record =
    { record | f2 = value }


s_f3 : a -> { b | f3 : a } -> { b | f3 : a }
s_f3 value record =
    { record | f3 = value }


s_f3_f1 : a -> { b | f3_f1 : a } -> { b | f3_f1 : a }
s_f3_f1 value record =
    { record | f3_f1 = value }


s_f3_f2 : a -> { b | f3_f2 : a } -> { b | f3_f2 : a }
s_f3_f2 value record =
    { record | f3_f2 = value }
`);
});
