const Parser = require("tree-sitter");
const Elm = require("tree-sitter-elm");
const fs = require("fs");
const path = require("path");

const parser = new Parser();
parser.setLanguage(Elm);

function sourceToIdentifiers(source, identifierSet = new Set()) {
  const tree = parser.parse(source);
  tree.rootNode
    .descendantsOfType(["field_type", "field", "record_pattern"])
    .flatMap((f) => {
      if (f.type === "record_pattern") {
        return f.descendantsOfType(["lower_case_identifier"]);
      } else {
        // Use only first lower_case_identifier before colon or equal in field def/expr
        return f.children.find((c) => c.type === "lower_case_identifier") || [];
      }
    })
    .forEach((identifier) => {
      identifierSet.add(identifier.text);
    });
  return identifierSet;
}

function moduleDeclaration(moduleName) {
  return `-- This module is generated by \`setem\` command. DO NOT edit manually!


module ${moduleName} exposing (..)
`;
}

function setterDefinition(prefix) {
  return function(recordFieldIdentifier) {
    return `${prefix}${recordFieldIdentifier} : a -> { b | ${recordFieldIdentifier} : a } -> { b | ${recordFieldIdentifier} : a }
${prefix}${recordFieldIdentifier} value__ record__ =
    { record__ | ${recordFieldIdentifier} = value__ }
`;
  }
}

const cwd = process.cwd();
function reducePerFile(identifierSet, filepath) {
  const abspath = path.resolve(cwd, filepath);
  const source = fs.readFileSync(abspath, { encoding: "utf8" });
  return sourceToIdentifiers(source, identifierSet);
}

function generate(filepaths = [], moduleName = "RecordSetter", prefix = "s_") {
  const uniqIdentifiers = [filepaths].flat().reduce(reducePerFile, new Set());
  const sortedUniqIdentifiers = [...uniqIdentifiers].sort();
  const setters = sortedUniqIdentifiers.map(setterDefinition(prefix));
  return [moduleDeclaration(moduleName), ...setters].join("\n\n");
}

module.exports = generate;
