name: sanity_check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  run-checks: # <== This name is referenced as a merge requirement for master branch
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 18
          - 20
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: v3-setem-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            v3-setem-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
      - run: npm run test:cli
