name: sanity_check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  run-checks: # <== This name is referenced as a merge requirement for master branch
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
          - 18
          - 20
          - 22
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: v3-setem-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            v3-setem-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run test:cli
  bun-checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - id: setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".tool-versions"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: bun-setem-${{ steps.setup-bun.outputs.bun-version }}-${{ hashFiles('bun.lockb') }}-${{ github.sha }}
          restore-keys: |
            bun-setem-${{ steps.setup-bun.outputs.bun-version }}-${{ hashFiles('bun.lockb') }}-
      - run: bun install
      - run: bun run lint
      - run: bun run test
      - run: bun run test:cli
